Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages'
Consider using the `--user` option or check the permissions.

ready satisfied: pip>=8.1.0 in /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages (from pypandoc~=1.3.0) (19.0.3)
Requirement already satisfied: setuptools in /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages (from pypandoc~=1.3.0) (40.8.0)
Installing collected packages: pypandoc
  Found existing installation: pypandoc 1.4
    Uninstalling pypandoc-1.4:
      Successfully uninstalled pypandoc-1.4
  Rolling back uninstall of pypandoc
  Moving to /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages/pypandoc-1.4.dist-info/
   from /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages/~ypandoc-1.4.dist-info
  Moving to /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages/pypandoc/
   from /home/not-yeshwanth-reddy/.local/lib/python3.6/site-packages/~ypandoc
